### ISSUE TITLE
"accidentdata.csv" file missing

### ISSUE THREAD

**Issue by steveny2k** [sfbrigade/datasci-dot-fars#2]
could you put "accidentdata.csv" into the project? thanks

**Comment by sirwart** [comment]
Just added the accident file. Right now it contains data back to 2001. The full data dictionary is [here](https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315) but if you click on columns [on this page](https://numeracy.co/sirwart/traffic-fatalities/accidents) you can also get a brief description.
